name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Echo supports last four Go major releases (1.22, 1.23, 1.24, 1.25)
        go: ["1.22", "1.23", "1.24", "1.25"]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make deps

      - name: Run Tests
        run: make test

      - name: Run Cookbook Tests
        run: make test-cookbook

      - name: Run Benchmarks
        run: make benchmark

